consumers/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'consumers'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name='upload'),
    path('api_getConsumers', views.api_getConsumers, name='api_getConsumers'),
]

pmu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from work.views import index

urlpatterns = [
    # path('', index),
    # path('', include('work.urls')),
    path('work/', include('work.urls')),
    path('admin/', admin.site.urls),
    path('consumers/', include('consumers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'work'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
    path('variations/<int:site_id>', views.variations, name='variations'),
    path('addVariation', views.addVariation, name='addVariation'),
    path('review/<int:pid>/<int:additional>', views.review, name='review'),
    path('resolution', views.resolution, name='resolution'),
    path('update_progress/', views.updateProgress, name="updateProgress"),
    path('undoextra/', views.undoextra, name="undoextra"),
    path('addSite/', views.addSite, name="addSite"),
    path('reloadSurveyData/', views.uploadSurvey, name='uploadSurvey'),
    path('loadDprQty/', views.loadDprQty, name='loadDprQty'),
    # path('loadDprHH/', views.loadDprHH, name='loadDprHH'),
    path('downloadFile/', views.downloadFile, name='downloadFile',),
    path('survey/<int:site_id>', views.survey, name='survey',),
    path('progress/<int:site_id>', views.progress, name='progress',),
    path('shifted/<int:site_id>', views.shifted, name='shifted',),
    path('resolutionlinkedpage/<int:id>', views.resolutionlinkedpage, name='resolutionlinkedpage',),
    path('updateProgress2/', views.updateProgress2, name='updateProgress2',),
    path('updateConfirmation/', views.updateConfirmation, name='updateConfirmation',),
    path('updateHabProgress/', views.updateHabProgress, name='updateHabProgress',),
    path('projectwise/', views.projectwise, name='projectwise'),
    path('divisionwise/', views.divisionwise, name='divisionwise'),

    # API's
    path('api_data/', views.api_data, name='api_data',),
    path('api_uploadDoc/', views.api_uploadDoc, name='api_uploadDoc',),
    path('api_deleteDoc/<str:model>/<int:id>', views.api_deleteDoc, name='api_deleteDoc',),
    path('api_getSite/', views.api_getSite, name='api_getSite',),
    path('api_markVariations', views.api_markVariations, name='api_markVariations',),
    path('api_markSiteOrigin', views.api_markSiteOrigin, name='api_markSiteOrigin',),
    path('api_mergeToSite', views.api_mergeToSite, name='api_mergeToSite',),
    path('api_load_review', views.api_load_review, name='api_load_review',),
    path('api_updateExecQty', views.api_updateExecQty, name='api_updateExecQty',),
    path('api_create_resolution_link', views.api_create_resolution_link, name='api_create_resolution_link',),
    path('api_switch_site', views.api_switch_site, name='api_switch_site',)
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.contrib import admin

admin.site.site_header = 'Project Monitoring'                    # default: "Django Administration"
admin.site.index_title = 'PMU Data Admin'                 # default: "Site administration"
admin.site.site_title = 'PMU Data Admin' # default: "Django site admin"

work/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

work/controller.py
import os
import math
from work.models import Site, ShiftedQty, ProgressQty, SurveyQty, ShiftedQtyExtra, ProgressQtyExtra, SiteExtra, DprQty, Log, Resolution, ResolutionLink, Log, Loa
import pandas as pd
from work.data import DISTRICTS_ALLOWED, DIVISIONS_ALLOWED, PROGRESS_QFIELDS, SURVEY_QFIELDS, REVIEW_QFIELDS, DPR_INFRA_FIELDS, SHIFTED_QFIELDS
from django.db.models import F, Sum, Count, Q, FileField
from work.functions import formatString
from work.models import getHabID
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Permission, User, Group
from django.contrib.auth.decorators import login_required
import pdb


def getSite(census, habitation):
    site = None
    additional = False
    habid = getHabID(census=census, habitation=formatString(habitation))
    site = Site.objects.filter(hab_id=habid).first()
    if(site):
        if(site.origin):
            site = site.origin
    else:
        #: if None, look into additional
        site = SiteExtra.objects.filter(hab_id=habid).first()
        if(site):
            if(site.site):
                site = site.site
            else:
                additional = True
    return site, additional


def getSiteData(census, habitation):
    site = None
    survey = None
    progress = None
    site, isAdd = getSite(census, habitation)
    if(not isAdd):
        survey = SurveyQty.objects.filter(site=site).first()
        progress = ProgressQty.objects.filter(site=site).first()
    return site, survey, progress


def getSiteProgressdf():
    site_fields = ['hab_id', 'village', 'census', 'habitation', 'district', 'division', 'category', 'project__name']
    qty_field = ['ht', 'pole_ht_8m', 'lt_3p', 'lt_1p', 'pole_lt_8m', 'dtr_100', 'dtr_63', 'dtr_25']
    # dfP = pd.DataFrame(ProgressQty.objects.all().values(*num_fields))
    # dfP.set_index('site__hab_id', inplace=True)
    # dfP['rem'] = 'site'
    # dfPX = pd.DataFrame(ProgressQtyExtra.objects.all().values(*num_fields))
    # dfPX.set_index('site__hab_id', inplace=True)
    # dfPX['rem'] = 'extra'
    #df = dfP.add(dfPX, fill_value=0, numeric_only=True)
    # df = pd.concat([dfP, dfPX])
    scope = Site.objects.exclude(Q(progressqty=None) & Q(surveyqty=None))
    sfield = ['surveyqty__' + f for f in qty_field]
    pfield = ['progressqty__'+f for f in qty_field]
    data = scope.values(*site_fields, *sfield, 'surveyqty__status', *pfield, 'progressqty__status', 'dprqty__project')
    df = pd.DataFrame(data)

    # copy progress data if survey data is blank. 
    _survey_infra = sum([df['surveyqty__' + f] for f in qty_field])
    _progress_infra = sum([df['progressqty__' + f] for f in qty_field])
    df['survey_infra'] = _survey_infra
    df['progress_infra'] = _progress_infra
    df = df[(_survey_infra > 0) | (_progress_infra > 0)]
    # df[(_survey_infra > 0)].loc[:,sfield] = df[(_survey_infra > 0)].loc[:,pfield]
    
    df.to_excel('outputs/progress_sites.xlsx')
    return df


def checkInfraNil(progress, shifted):
    hasError = False
    res = []
    # values = [getattr(progress, f, 0) or 0 for f in PROGRESS_QFIELDS]
    # qtysum = sum([v for v in values if not v == None])
    try:
        pqtysum = sum([getattr(progress, f, 0) or 0 for f in PROGRESS_QFIELDS])
        sqtysum = sum([getattr(shifted, f, 0) or 0 for f in SHIFTED_QFIELDS])
        if(not (pqtysum > 0 and sqtysum > 0)):
            hasError = True
            res.append({'class': 'error', 'text': '{}: infra is nil'.format(progress)})
        return hasError, res
    except Exception as ex:
        hasError = True
        res.append({'class': 'error', 'text': '{}: {}'.format(progress.site, ex.__str__())})
        return hasError, res


def checkAgainstSurvey(site, progress):
    survey = SurveyQty.objects.filter(site=site).first()
    res = []
    hasError = False
    for f in PROGRESS_QFIELDS:
        # print('comparing {} against survey'.format(f))
        try:
            diff = (getattr(progress, f, 0) or 0) - (getattr(survey, f, 0) or 0)  # if access 20%
            comp = (getattr(progress, f, 0) or 0) > 1.2 * (getattr(survey, f, 0) or 0)  # if access 20%
            if(comp):
                res.append(
                    {'class': 'warning', 'text': 'excess {} {}:\t\t{} \tby {}'.format(site.census, site.habitation, f, round(diff,1))})
        except Exception as ex:
            res.append(
                    {'class': 'error', 'text': '{}: {}'.format(progress.site, ex.__str__())})
    return hasError, res


def validateProgressFile(file):
    status = []
    hasError = False
    try:
        df = pd.read_excel(file, sheet_name='upload', header=None)
    except Exception as ex:
        hasError=True
        status.append({'class':'error','text': ex.__str__()})
        return hasError, status, None
    data_row = 6
    # check format
    dfTemplate = pd.read_excel('files/progress_report.xlsx', header=None)
    try: 
        columns = dfTemplate.iloc[data_row-1]
        for i in range(24):
            if(df.iloc[data_row-1, i] != columns[i]):
                status.append(
                    {'class': 'error', 'text': 'Format error @: {}'.format(columns[i])})
                hasError = True
        if(hasError):
            return hasError, status, None
        df_data = df[data_row:]
        df_data.iloc[:, 7:23].fillna(value=0, inplace=True)
        df_data.iloc[:, 7:23].replace('', 0, inplace=True)
        df_data = df_data.rename(columns=df.iloc[5, :])
        df_data = df_data.fillna('')
    except Exception as ex:
        return True, [{'class':'error', 'text': ex.__str__()}], None
    return hasError, status, df_data


def _assignQty(pqty, sqty, data):
    fields_shifted = ['acsr', 'cable_3p', 'cable_1p',
                      'pole_8m', 'pole_9m', 'dtr_100', 'dtr_63', 'dtr_25']
    for field in fields_shifted:
        setattr(sqty, field, getattr(data, field + '_shifted', 0))

    fields_progress = ['ht', 'pole_ht_8m', 'lt_3p', 'lt_1p',
                       'pole_lt_8m', 'dtr_100', 'dtr_63', 'dtr_25', 'remark', 'status']
    for field in fields_progress:
        setattr(pqty, field, getattr(data, field, 0))

    return pqty, sqty


def updateProgressSingle(progressdata, updateid, isTest):
    updated = False
    status = []
    hasError = False
    village = formatString(progressdata['village'])
    census = progressdata['census']
    habitation = formatString(progressdata['habitation'])
    site, additional = getSite(census, habitation)
    pqty = None
    sqty = None
    print('Processing... {}'.format(site))
    if(site and not additional):
        sqty = ShiftedQty.objects.filter(site=site).first()
        if(not sqty):
            sqty = ShiftedQty(site=site)
        pqty = ProgressQty.objects.filter(site=site).first()
        if(not pqty):
            pqty = ProgressQty(site=site)
        status.append(
            {'class': 'success', 'text': 'Updating: {village} {census} {habitation}'.format(**progressdata)})
    elif(site and additional):
        sqty = ShiftedQtyExtra.objects.filter(site=site).first()
        if(not sqty):
            sqty = ShiftedQtyExtra(site=site)
        pqty = ProgressQtyExtra.objects.filter(site=site).first()
        if(not pqty):
            pqty = ProgressQtyExtra(site=site)
        # _assignQty(pqty, sqty, progressdata)
        # pqty.changeid = updateid
        # sqty.changeid = updateid
        status.append(
            {'class': 'success', 'text': 'Updating (additional): {village} {census} {habitation}'.format(**progressdata)})
    else:
        #: another additional site... requires formal approval
        status.append(
            {'class': 'error', 'text': "Unknown site: {village} {census} {habitation}".format(**progressdata)})
        hasError = True
    if(pqty):
        # skip update if...
        # if((not pqty.review == 'not reviewed' ) or (pqty.status == 'completed') or (pqty.cert == True)):
        if((not pqty.review == 'not reviewed' ) or (pqty.cert == True)):
            status.append(
            {'class': 'info', 'text': "skipped: {village} {census} {habitation} completed, under review".format(**progressdata)})            
            return False, status, False

        _assignQty(pqty, sqty, progressdata)
        hasError, warnings = checkAgainstSurvey(site, pqty)
        status.extend(warnings)

        pqty.changeid = updateid
        sqty.changeid = updateid        
        hasError, errors = checkInfraNil(pqty, sqty)
        status.extend(errors)
    # input('check')
    if(not isTest and not hasError):
        pqty.save()
        sqty.save()
        print('saving...')
        status.append(
            {'class': 'success', 'text': "Updated {village} {census} {habitation}".format(**progressdata)})
        updated = True
    # print(status)
    return hasError, status, updated


def UpdateProgress(file, updateid, isTest):
    status = []
    hasError, dfstatus, dfProgress = validateProgressFile(file)
    updated = False
    if(hasError):
        status.extend(dfstatus)
        # print(status)
        return status
    for index, row in dfProgress.iterrows():
        iferror, stat, updated = updateProgressSingle(row, updateid, isTest)
        status.extend(stat)
    if(updated and not isTest):
        log = Log(model='Progress', changeid=updateid)
        log._save()
    # print(status)
    return status


def getDistrictProgressSummary():
    num_fields = ['ht', 'ht_conductor', 'pole_ht_8m', 'lt_3p', 'lt_1p',
                  'pole_lt_8m', 'dtr_100', 'dtr_63', 'dtr_25']
    df_district = pd.DataFrame(ProgressQty.objects.values(
        district=F('site__district')).annotate(
            *[Sum(f) for f in num_fields],
            completed=Count('status', filter=Q(status='completed')),
            cert=Count('cert', filter=Q(cert=True))
    ))
    df_district.set_index('district', inplace=True)

    df_extra = pd.DataFrame(ProgressQtyExtra.objects.values(
        district=F('site__district')).annotate(

work/templates/work/base.html
<html>

<head>
    {% load static %}
    <link href="{% static 'work/style.css' %}" rel="stylesheet">
    <!-- <link href="{% static 'work/css/materialize.min.css' %}" rel="stylesheet">
    <link href="{% static 'work/js/materialize.min.js' %}" rel="text/javascript"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
</head>

<body>
    <div id="base">
        <!-- <div id='nav' :class="{'section':true, 'leftnavExpanded': navCollapse,'leftnavMini': !navCollapse}"> -->
        <div id='nav'>
            <!-- <div @click="leftNav = !leftNav">{: leftNav? 'Minimize':'Show' :}</div> -->
            <ul>
                <strong>Project Monitoring</strong>
                <li><a target="_blank" href="{% url 'work:index' %}">Summary</a></li>
                <li><a target="_blank" href="{% url 'work:detail' %}">Details</a></li>
                <li><a target="_blank" href="{% url 'consumers:index' %}">Consumers</a></li>
                <li><a target="_blank" href="{% url 'work:resolution' %}">Resolution/Issues</a></li>
                <li><a target="_blank" href="{% url 'work:updateProgress2' %}">Update Progress</a></li>
                <li><a target="_blank" href="{% url 'work:projectwise' %}">Projectwise Overview</a></li>
                <li><a target="_blank" href="{% url 'work:divisionwise' %}">Divisionwise Overview</a></li>
            <!-- <li><a target="_blank" href="#upload_surveydata">Upload Survey Data</a></li> -->
                <!-- <li><a target="_blank" href="#recent_changes">Recent Changes</a></li> -->
                <!-- <li><a target="_blank" href="#reload_dpr">Load DPR</a></li> -->
            </ul>
        </div>
    </div>

    <div id='content'>
        {% if messages %}
        <div class="flash">
            <ul>
                {% for message in messages %}
                <li class="{{message.tags}}">{{ message | safe}}</li>
                {% endfor %}
            </ul>

        </div>
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    <div id="right">
        {% block right %}
        {% endblock %}
    </div>
    <div style="height: 20vh;"></div>
    </div>
    <!-- <script type="text/javascript" src="{% static 'work/js/materialize.min.js' %}"></script> -->
    <script type="text/javascript" src="{% static 'work/js/jquery-3.4.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'work/js/vue.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'work/js/axios.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'work/js/js.cookie.min.js' %}"></script>
    {% block script %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'work/js/script.js' %}"></script>
</body>

</html>

work/templates/work/divisionwise.html
{% extends "work/base.html" %}
{% load static %}
{% block content %}
<!-- <form id="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
    {% csrf_token %}
    <input hidden name='path' value="outputs/project_hab_progress.xlsx">
    <input hidden name='filename' value="project_hab_progress.xlsx">
    <input hidden name='tabtype' value="project_hab_progress">
    <input type="submit" value="Download Progress Hab Progress">
</form> -->
{{ data | safe }}
{% endblock %}

work/templates/work/index.html
{% extends "work/base.html" %}
{% load static %}
{% block content %}
{% include "work/_resolutionbox.html"%}
<div id="index">
    <div v-if="output">
        <b>Output</b><br>
        <label>Errors only <input type="checkbox" v-model="errors_only"></label>
        <label>warnings only <input type="checkbox" v-model="warnings_only"></label>
        <ol style="list-style-position: unset; list-style:none;overflow: scroll; max-height: 20ch;">
            <table>
                <tr v-for="item in output" :class="item['class']"
                    v-if="(errors_only && item['class']=='error') || (warnings_only && item['class']=='warning') || (!errors_only && !warnings_only)">
                    <td>{: item['text'] :}</td>
                </tr>
            </table>
        </ol>
    </div>
    <button v-on:click="toggleAdmin">Admin on/off</button>
    <div v-if="admin" class="section">
        <p>Load DPR Qty</p>
        <form action="{% url 'work:loadDprQty'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file" accept=".xlsx">
            <input type="submit" value="Load">
        </form>
    </div>

    <div v-if="admin" class="section">
        <h2>Saubhagya (DDUGJY Additional Infra)</h2>
        <form id="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
            {% csrf_token %}
            <input hidden name='path' value="files/template_approval.xlsx">
            <input hidden name='filename' value="template_approval.xlsx">
            <input hidden name='tabtype' value="template_approval">
            <input type="submit" value="Download template_approval">
        </form>
        <h3>Upload Survey Data</h3>
        <form action="{% url 'work:uploadSurvey'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file" accept=".xlsx">
            <input type="submit" value="upload">
        </form>
    </div>
    <div v-if="admin" class="section">
        <p>Add site</p>
        <form action="{% url 'work:addSite'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Select update file</p>
            <input type="file" name="file" accept=".xlsx">
            <input type="submit" value="Add">
        </form>
    </div>
    <br>
    <div class="section">
        <h4>Update progress</h4>
        <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
            {% csrf_token %}
            <input hidden name='path' value="files/progress_report.xlsx">
            <input hidden name='filename' value="template_progress_report.xlsx">
            <input hidden name='tabtype' value="template_progress_report">
            <input type="submit" value="Download Report Template">
        </form>
        <form @submit.prevent="updateProgress(false)">
            {% csrf_token %}
            <p>Select update file</p>
            <label for="changeid">Update id</label>
            <input type="text" name="updateid" v-model="updateid">
            <input type="file" name="file" accept=".xlsx" v-on:change="handleFileUpload" ref="file">
            <button v-on:click="updateProgress(true)" id="validate_progress" v-bind:disabled="!if_file">Check</button>
            <input type="submit" value="update" v-bind:disabled="!if_file">
        </form>
    </div>
    <!-- Undo -->
    <hr>
    <div v-if="admin">
        <form action="{% url 'work:undoextra'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><b>Undo Extra Site Qty Update</b></p>
            <label for="changeid">Update id</label>
            <input type="text" name="updateid">
            <input type="submit" value="Undo">
        </form>
    </div>
    <br>
    <div style="display: flex;">
        <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
            {% csrf_token %}
            <input hidden name='path' value="outputs/progess_summary.xlsx">
            <input hidden name='filename' value="DistrictProgressSummary.xlsx">
            <input hidden name='tabtype' value="districtwise">
            <input type="submit" value="Download District Progress">
        </form>
        <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
            {% csrf_token %}
            <input hidden name='path' value="outputs/progress_sites.xlsx">
            <input hidden name='filename' value="progress_sites.xlsx">
            <input hidden name='tabtype' value="sites">
            <input type="submit" value="Download Site Scope & Progress">
        </form>
        <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
            {% csrf_token %}
            <input hidden name='path' value="outputs/balance_progress.xlsx">
            <input hidden name='filename' value="balance_progress.xlsx">
            <input hidden name='tabtype' value="balance">
            <input type="submit" value="Download Balance and Progress">
        </form>
    </div>
    <div>
        <div v-if="ifloading">
            Loading...
        </div>
        <b>Progress</b>
        <span v-html="data"></span>
    </div>
    <a name="recent_changes"></a>
    <div class="section">
        <p><b>Last changes</b></p>
        <ul style="list-style: none;">
            <li v-for="log in logs">
                {: log['created_at'].substring(0,10) :} {: log['changeid'] :} - {: log['model'] :}
            </li>
        </ul>
    </div>
</div>
{% endblock %}
{% block right %}
{% endblock %}
{% block script %}
<script>
    indexApp = new Vue({
        el: '#index',
        delimiters: ["{:", ":}"],
        data: {
            show: true,
            admin: false,
            output: null,
            hasOutput: false,
            if_file: false,
            updateid: "",
            errors_only: false,
            warnings_only: false,
            data: null,
            logs: null,
            ifloading: false
        },
        mounted() {
            this.getData();
        },
        methods: {
            getData: function () {
                this.ifloading = true;
                axios.get("{% url 'work:api_data' %}").then(response => {
                    this.data = response.data['data'];
                    this.logs = response.data['logs'];
                    tdcss();
                    //console.log(this.logs);
                    this.ifloading = false;
                });
            },
            toggleAdmin: function () {
                this.admin = !this.admin
            },
            updateProgress: function (isTest) {
                ifloading = true;
                this.output = null;
                let file = this.$refs.file.files[0];
                let formdata = new FormData();
                formdata.append('file', file);
                formdata.append('updateid', this.updateid);
                formdata.append('isTest', isTest);
                let csrftoken = Cookies.get('csrftoken');
                axios.post("{% url 'work:updateProgress' %}", formdata,
                    {
                        headers: {
                            'Content-Type': 'multipart/form-data',
                            'X-CSRFToken': csrftoken
                        }
                    }
                ).then(response => {
                    this.output = response.data['status'];
                    console.log(response.data);
                    this.errors_only = false;
                    ifloading = false;
                    this.getData();
                }).catch(ex => {
                    console.log(ex);
                    ifloading = false;
                });
            },
            handleFileUpload: function () {
                if (this.$refs.file.files[0]) {
                    this.updateid = this.$refs.file.files[0].name;
                    this.if_file = true
                }
                else
                    this.if_file = false
            }
        }
    });
</script>
{% endblock %}

work/templates/work/projectwise.html
{% extends "work/base.html" %}
{% load static %}
{% block content %}
<form id="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
    {% csrf_token %}
    <input hidden name='path' value="outputs/project_hab_progress.xlsx">
    <input hidden name='filename' value="project_hab_progress.xlsx">
    <input hidden name='tabtype' value="project_hab_progress">
    <input type="submit" value="Download Progress Hab Progress">
</form>
{{ data | safe }}
{% endblock %}

work/templates/work/resolution.html
{% extends "work/base.html" %}
{% block content %}
<div>
    <div style="display: flex; justify-content:space-evenly; margin: 8px; width:30em">
        <b>Resolution Center</b>
        <a href="/admin/work/resolution/add/" target="_blank">Add</a>
        <a href="/admin/work/resolution/" target="_blank">View all</a>
    </div>

    <table style="text-align: left;">
        {% for res in resolutions %}
        <tr>
            <td><a href="{% url 'work:resolutionlinkedpage' res.id%}" style="text-decoration: none;"
                    target="_blank">{{res}}</a></td>
            <td>
                {% if res.deadline %}
                {{res.deadline}}
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

work/templates/work/resolution_page.html
{% extends 'work/base.html' %}
{% block content %}
<div style="display: flex; flex-direction:row; height:100%" id="res">
    <div style="flex:1">
        <iframe src="{{res_link}}" width="100%" height="100%"></iframe>
    </div>
    <div style="padding:8px;flex:2;">
        {% if link %}
        <a href="{{link}}" target="_blank">Open in separate window</a>
        <iframe src="{{link}}" width="100%" height="100%"></iframe>
        {% endif %}
    </div>
</div>
{% endblock %}

work/templates/work/variations.html
{% extends "work/base.html" %}
{% block content %}
{% include "work/_resolutionbox.html"%}
{% load static %}
<div id="filterapp">
    <div v-if="site">
        Site id
        <div v-for="(val, key) in site">
            {:key:}: {:val:}
        </div>
    </div>
    <hr>
    <div>
        <b>Variations</b>
        <table>
            <thead>
                <th>village</th>
                <th>census</th>
                <th>habitation</th>
                <th>edit</th>
            </thead>
            <tbody>
                <tr v-for="site in variants">
                    <td>{: site['village']:}</td>
                    <td>{: site['census']:}</td>
                    <td>{: site['habitation']:}</td>
                    <td><a :href="'/admin/work/siteextra/' + site['id']" target="_blank">edit</a></td>
                </tr>
            </tbody>
        </table>
    </div>
    <hr>
    <div>
        <input v-model="village" placeholder="village">
        <input v-model="census" placeholder="census">
        <input v-model="habv1" placeholder="habitation variant">
        <button @click="addVariation">add</button>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    new Vue(
        {
            el: "#filterapp",
            delimiters: ["{:", ":}"],
            mounted() {
                this.site_id = "{{site_id}}";
                console.log(this.site_id);
                this.fetchSite();
            },
            data: {
                site_id: null,
                variants: [],
                habv1: null,
                site: null,
                census: null,
                village: null,
            },
            methods: {
                fetchSite: function () {
                    let formdata = new FormData();
                    axios.post("{% url 'work:variations' site_id %}", formdata, {
                        headers: {
                            'X-CSRFToken': Cookies.get('csrftoken')
                        }
                    }).then(response => {
                        console.log(response.data);
                        this.variants = response.data['variants']
                        this.site = response.data['site']
                        this.habv1 = this.site['habitation']
                        this.census = this.site['census']
                        this.village = this.site['village']
                    });
                },
                addVariation: function () {
                    let formdata = new FormData();
                    formdata.append('habitation', this.habv1);
                    formdata.append('census', this.census);
                    formdata.append('village', this.village);
                    formdata.append('site_id', this.site_id);
                    axios.post("{% url 'work:addVariation' %}", formdata, {
                        headers: {
                            'X-CSRFToken': Cookies.get('csrftoken')
                        }
                    }).then(response => {
                        console.log(response.data);
                        this.fetchSite();
                        this.habv1 = null;
                    });
                }
            },
        }
    );
</script>
{% endblock %}