consumers/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'consumers'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.upload, name='upload'),
    path('api_getConsumers', views.api_getConsumers, name='api_getConsumers'),
]

pmu/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from work.views import index

urlpatterns = [
    # path('', index),
    # path('', include('work.urls')),
    path('work/', include('work.urls')),
    path('admin/', admin.site.urls),
    path('consumers/', include('consumers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

work/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
app_name = 'work'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
    path('variations/<int:site_id>', views.variations, name='variations'),
    path('addVariation', views.addVariation, name='addVariation'),
    path('review/<int:pid>/<int:additional>', views.review, name='review'),
    path('resolution', views.resolution, name='resolution'),
    path('update_progress/', views.updateProgress, name="updateProgress"),
    path('undoextra/', views.undoextra, name="undoextra"),
    path('addSite/', views.addSite, name="addSite"),
    path('reloadSurveyData/', views.uploadSurvey, name='uploadSurvey'),
    path('loadDprQty/', views.loadDprQty, name='loadDprQty'),
    # path('loadDprHH/', views.loadDprHH, name='loadDprHH'),
    path('downloadFile/', views.downloadFile, name='downloadFile',),
    path('survey/<int:site_id>', views.survey, name='survey',),
    path('progress/<int:site_id>', views.progress, name='progress',),
    path('shifted/<int:site_id>', views.shifted, name='shifted',),
    path('resolutionlinkedpage/<int:id>', views.resolutionlinkedpage, name='resolutionlinkedpage',),
    path('updateProgress2/', views.updateProgress2, name='updateProgress2',),
    path('updateConfirmation/', views.updateConfirmation, name='updateConfirmation',),
    path('updateHabProgress/', views.updateHabProgress, name='updateHabProgress',),
    path('projectwise/', views.projectwise, name='projectwise'),
    path('divisionwise/', views.divisionwise, name='divisionwise'),

    # API's
    path('api_data/', views.api_data, name='api_data',),
    path('api_uploadDoc/', views.api_uploadDoc, name='api_uploadDoc',),
    path('api_deleteDoc/<str:model>/<int:id>', views.api_deleteDoc, name='api_deleteDoc',),
    path('api_getSite/', views.api_getSite, name='api_getSite',),
    path('api_markVariations', views.api_markVariations, name='api_markVariations',),
    path('api_markSiteOrigin', views.api_markSiteOrigin, name='api_markSiteOrigin',),
    path('api_mergeToSite', views.api_mergeToSite, name='api_mergeToSite',),
    path('api_load_review', views.api_load_review, name='api_load_review',),
    path('api_updateExecQty', views.api_updateExecQty, name='api_updateExecQty',),
    path('api_create_resolution_link', views.api_create_resolution_link, name='api_create_resolution_link',),
    path('api_switch_site', views.api_switch_site, name='api_switch_site',)
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


from django.contrib import admin

admin.site.site_header = 'Project Monitoring'                    # default: "Django Administration"
admin.site.index_title = 'PMU Data Admin'                 # default: "Site administration"
admin.site.site_title = 'PMU Data Admin' # default: "Django site admin"

consumers/models.py
from django.db import models
from work.models import Site


class Timestamp(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,  blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True,  blank=True, null=True)

    class Meta:
        abstract = True


class Common(Timestamp):
    changeid = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        abstract = True


class Consumer(Common):
    def __str__(self):
        return "{} - {} - ({}) - {} portal({})".format(self.name, self.consumer_no, self.habitation, self.census, self.isInPortal)

    class Meta:
        unique_together = ('census', 'habitation', 'name', 'consumer_no')
    site = models.ForeignKey(
        Site, on_delete=models.SET_NULL, null=True, blank=True)
    hab_id = models.CharField(max_length=50, null=True, blank=True)
    village = models.CharField(max_length=50, null=True, blank=True)
    census = models.IntegerField()
    habitation = models.CharField(max_length=50,  null=True, blank=True)
    name = models.CharField(max_length=50)
    consumer_no = models.CharField(max_length=50, null=True, blank=True)
    edate = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=20, null=True, blank=True)
    aadhar = models.CharField(max_length=50, null=True, blank=True)
    meter_no = models.CharField(max_length=50, null=True, blank=True)
    apl_bpl = models.CharField(max_length=3, null=True, blank=True)
    mobile_no = models.CharField(max_length=20, null=True, blank=True)
    voter_no = models.CharField(max_length=20, null=True, blank=True)
    tariff = models.CharField(max_length=20, null=True, blank=True)
    pdc_date = models.CharField(max_length=20, null=True, blank=True)
    address1 = models.CharField(max_length=100, null=True, blank=True)
    address2 = models.CharField(max_length=100, null=True, blank=True)
    remark = models.CharField(max_length=100, null=True, blank=True)
    isInPortal = models.BooleanField(null=True, blank=True)
    district = models.CharField(max_length=20, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.habitation = " ".join(str(self.habitation).split()).upper()
        self.name = " ".join(str(self.name).split()).upper()
        self.consumer_no = str(self.consumer_no).replace(" ", "").upper()
        super(Consumer, self).save(*args, **kwargs)

consumers/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from django.views.decorators.csrf import ensure_csrf_cookie
from django.http import JsonResponse
import pandas as pd
from django.contrib import messages
from .models import Consumer
from work.models import Site
from work.functions import getHabID,formatString
from django.db.models import F, Sum, Count, Q, FileField

@ensure_csrf_cookie
def index(request):
    data = getData()
    return render(request, "consumers/index.html", {'data': data})


def getData():
    c = Consumer.objects.values('district').annotate(records=Count('name'))
    df = pd.DataFrame(c).fillna('None')
    df.set_index('district',inplace=True)
    c = Consumer.objects.filter(isInPortal=True).values('district').annotate(count=Count('name'))
    dfp = pd.DataFrame(c).fillna('None')
    dfp.set_index('district',inplace=True)    
    df['in portal '] = dfp
    return df.to_html()


def upload(request):
    if(not request.method == 'POST'):
        return render(request, "consumers/index.html")
    file = request.FILES['file']
    upid = request.POST['upid']
    df = pd.read_excel(file, 'upload')
    df = df.fillna('')
    df_template = pd.read_excel('files/template_consumer_details.xlsx')
    cols = df_template.columns
    truths = [col in df.columns for col in df_template.columns]
    ifmatch = all(truths)
    ncreated = 0
    nupdated = 0
    if(not ifmatch):
        notmatch = [df_template.columns[i]
                    for i, col in enumerate(truths) if not col]
        messages.error(request, "Field not found– ")
        messages.error(request, notmatch)
        return HttpResponseRedirect(reverse('consumers:index'))
    for index, row in df.iterrows():
        # unique_together = ('census', 'habitation', 'name', 'consumer_no')
        print('Processing..')
        print(row)
        consumer, created = Consumer.objects.get_or_create(
            census=row[cols[0]],
            habitation=" ".join(str(row[cols[1]]).split()).upper(),
            name=" ".join(str(row[cols[3]]).split()).upper(),
            consumer_no=str(row[cols[7]]).replace(" ", "").upper()
        )
        if(created):
            ncreated += 1
        else:
            nupdated += 1
        # consumer.village = row[cols[]]
        consumer.edate = row[cols[2]]
        consumer.status = row[cols[11]]
        consumer.aadhar = row[cols[5]]
        consumer.meter_no = row[cols[8]]
        consumer.apl_bpl = row[cols[6]]
        consumer.mobile_no = row[cols[4]]
        consumer.voter_no = row[cols[9]]
        consumer.tariff = row[cols[10]]
        consumer.pdc_date = row[cols[12]]
        consumer.address1 = row[cols[13]]
        consumer.address2 = row[cols[14]]
        consumer.remark = row[cols[15]]
        censusSite = Site.objects.filter(census = row[cols[0]]).first()
        if(censusSite):
            consumer.district = censusSite.district
            consumer.village = censusSite.village

        consumer.changeid = upid
        hab_id = getHabID(census=row[cols[0]], habitation=row[cols[1]])
        if(Site.objects.filter(hab_id=hab_id).exists()):
            site = Site.objects.get(hab_id=hab_id)
            consumer.site = site
        try:
            consumer.save()
        except Exception as ex:
            messages.error(request, ex.__str__())
            print('Processing..')
            print(row)
            print(ex)
    messages.success(request, '{} updated. {} uploaded of {} records'.format(
        nupdated, ncreated, len(df)))
    return HttpResponseRedirect(reverse('consumers:index'))


def api_getConsumers(request):
    if(request.method != 'POST'):
        return JsonResponse(
            'nothing to do'
        )
    filterString = {}
    habid = request.POST.get('habid', None)
    if(habid):
        filterString['hab_id__icontains'] = habid
    habid_exact = request.POST.get('habid_exact',None)
    if(habid_exact):
        filterString['hab_id__exact'] = habid_exact
    inPortal = request.POST.get('inPortal',None)
    if(inPortal):
        filterString['isInPortal'] = True
    village = request.POST.get('village', None)
    village = formatString(village)
    if(village):
        filterString['village__icontains'] = village

    consumers = Consumer.objects.filter(**filterString)
    df = pd.DataFrame(consumers.values()).iloc[:, 4:]
    df.to_excel('outputs/filtered_consumers.xlsx')
    return JsonResponse(
        {
            'consumers': df.to_html()
        })

consumers/templates/consumers/index.html
{% extends "work/base.html" %}

{% block content %}
<!--- Upload consumer records -->
<p>Upload consumer data</p>
<div id="appConsumer">
    <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
        {% csrf_token %}
        <input hidden name='path' value="files/template_consumer_details.xlsx">
        <input hidden name='filename' value="template_consumer_details.xlsx">
        <input hidden name='tabtype' value="template_consumer_details">
        <input type="submit" value="Download Consumer Details Template">
    </form>
    <form action="{% url 'consumers:upload'%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Upload id</label>
        <input type="text" name="upid" v-model="upid" @change="changed">
        <input type="file" name="file" accept=".xlsx" @change="changed" v-model="file">
        <input type="submit" value="upload" :disabled="!isValid">
    </form>
    <div class="section">
        <strong>Consumers Count</strong>
        {{data | safe}}
    </div>
    <div class="section">
        <form @submit.prevent="loadConsumers()" style="display: flex; flex-direction:row; justify-content:flex-start;">
            <label>Village</label>
            <input type="text" name="village" id="village" v-model="village">
            <label>census + habitation</label>
            <input type="text" name="habid" id="habid" v-model="habid" autofocus>
            <label>Hab id</label>
            <input type="text" name="habid_exact" id="habid_exact" v-model="habid_exact" autofocus>
            <label><input type="checkbox" name="portalonly" id="portal" v-model="inPortal">Only Portal</label>
            <input type="submit" :disabled="!habid && !habid_exact && !village" value="Load">
        </form>
        <hr>
    </div>
    <form class="downloadSummary" method="POST" action="{% url 'work:downloadFile' %}">
        {% csrf_token %}
        <input hidden name='path' value="outputs/filtered_consumers.xlsx">
        <input hidden name='filename' value="filtered_consumers.xlsx">
        <input hidden name='tabtype' value="filtered_consumers">
        <input type="submit" value="Download">
    </form>
    <div v-if="consumers" class="section">
        <span v-html="consumers"></span>
    </div>
</div>
{% endblock %}
{% block right %}
{% endblock %}
{% block script %}
<script>
    new Vue({
        el: "#appConsumer",
        delimiters: ["{:", ":}"],
        data: {
            isValid: false,
            upid: null,
            file: null,
            habid: null,
            habid_exact: null,
            village: null,
            consumers: null,
            inPortal: false
        },
        methods: {
            changed: function () {
                if (this.upid == null)
                    this.upid = this.file;
                this.isValid = this.file != null && this.upid != null;
            },
            loadConsumers: function () {
                this.consumers = null;
                let formdata = new FormData();
                if (this.habid)
                    formdata.append('habid', this.habid.replace(" ", ""));
                if (this.habid_exact)
                    formdata.append('habid_exact', this.habid_exact.replace(" ", ""));
                if (this.village)
                    formdata.append('village', this.village.replace(" ", ""));
                if (this.inPortal)
                    formdata.append('inPortal', 'True');
                axios.post("{% url 'consumers:api_getConsumers' %}", formdata, {
                    headers: {
                        'X-CSRFToken': Cookies.get('csrftoken')
                    }
                }).then(response => {
                    this.consumers = response.data['consumers'];
                });
            }
        }

    });
</script>

{% endblock %}